# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: setup
    init: |
          mvn clean package
          docker-compose build
    command: | 
            docker-compose up

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
  - port: 8001
    onOpen: open-browser
    visibility: public
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - pivotal.vscode-boot-dev-pack
    

